### ISSUE TITLE
Please stop using t,k,m,n,f as variable name in example

### ISSUE THREAD

**Issue by EtBLh** [MisterKeefe/dom-particles#3]
It's hard to understand how to use the library with only some examples provided, especially some variable names is only one alphabet.

**Comment by MisterKeefe** [comment]
Great point, thank you. I've refactored the variable names in [the examples code file](https://github.com/MisterKeefe/dom-particles/blob/master/examples/index.js) to be a bit more explicit and use fewer single-character names. 

Is there a particular example you'd like a bit more detail on?

**Comment by EtBLh** [comment]
Thank you, that helps a lot. I have figured out the usage of it.
btw the repo and homepage link of npm package page doesn't seem to work well, could you fix it?

**Comment by MisterKeefe** [comment]
Thanks for pointing out those broken links, I've published a new patch version to fix them. I'm going to close this issue now -- let me know if there's anything else I can help with!
